import type { Project } from '@/lib/types';

const today = new Date();

function addDays(days: number) {
  const nextDate = new Date(today);
  nextDate.setDate(nextDate.getDate() + days);
  return nextDate.toISOString();
}

export const seedProjects: Project[] = [
  {
    id: 'aggrandize-rebrand',
    name: 'Aggrandize Platform Rebrand',
    description:
      'Refresh completo da experiência do produto com foco em clareza operacional, onboarding e comunicação de valor para times de serviços.',
    manager: 'Helena Costa',
    activeSprint: 'Sprint 08 · Atualização do produto',
    health: 'On track',
    expectedEndDate: addDays(18),
    goals: [
      'Validar uma navegação clara para planner, backlog e saúde do projeto.',
      'Apresentar um dashboard executivo com métricas úteis para liderança.',
      'Demonstrar um fluxo de autenticação simplificado para stakeholders.',
    ],
    tags: ['Frontend', 'Design System', 'Discovery'],
    metrics: {
      velocity: 24,
      blocked: 1,
      throughput: 11,
    },
    members: [
      {
        id: 'member-helena',
        name: 'Helena Costa',
        email: 'helena@aggrandize.com',
        role: 'Product Manager',
        level: 'Lead',
        workloadScore: 4,
        capacity: 10,
        workloadStatus: 'Relaxed',
        focus: 'Priorizar rollout do MVP',
        availability: 'Available',
      },
      {
        id: 'member-livia',
        name: 'Livia Barros',
        email: 'livia@aggrandize.com',
        role: 'Frontend Engineer',
        level: 'Senior',
        workloadScore: 9,
        capacity: 13,
        workloadStatus: 'Healthy',
        focus: 'Implementar dashboard e páginas do planner',
        availability: 'Busy',
      },
      {
        id: 'member-matheus',
        name: 'Matheus Rocha',
        email: 'matheus@aggrandize.com',
        role: 'Product Designer',
        level: 'Mid',
        workloadScore: 6,
        capacity: 10,
        workloadStatus: 'Healthy',
        focus: 'Ajustar estados de erro, loading e responsividade',
        availability: 'Available',
      },
    ],
    tasks: [
      {
        id: 'task-landing',
        title: 'Criar landing page orientada a valor',
        description: 'Destacar benefícios, métricas e CTA para entrada no workspace.',
        status: 'done',
        difficulty: 3,
        progress: 100,
        priority: 'High',
        roleRequired: 'Frontend Engineer',
        assigneeId: 'member-livia',
        dueDate: addDays(1),
        tags: ['Marketing', 'Landing'],
        reports: [
          {
            id: 'report-landing-1',
            author: 'Livia Barros',
            message: 'Hero publicado com seções de métricas e proposta de valor.',
            createdAt: addDays(-1),
          },
        ],
      },
      {
        id: 'task-dashboard',
        title: 'Montar dashboard executivo',
        description: 'Cards de métricas, busca por projeto e snapshot de saúde operacional.',
        status: 'doing',
        difficulty: 5,
        progress: 72,
        priority: 'High',
        roleRequired: 'Frontend Engineer',
        assigneeId: 'member-livia',
        dueDate: addDays(3),
        tags: ['Dashboard', 'Métricas'],
        reports: [],
      },
      {
        id: 'task-detail',
        title: 'Detalhar visão do projeto',
        description: 'Listar tarefas por status, equipe, riscos e registro rápido de updates.',
        status: 'todo',
        difficulty: 5,
        progress: 0,
        priority: 'Medium',
        roleRequired: 'Frontend Engineer',
        dueDate: addDays(6),
        tags: ['Detalhe do projeto'],
        reports: [],
      },
      {
        id: 'task-system',
        title: 'Consolidar design system base',
        description: 'Componentes reutilizáveis para badge, botão, cards e formulários.',
        status: 'blocked',
        difficulty: 3,
        progress: 35,
        priority: 'Medium',
        roleRequired: 'Product Designer',
        assigneeId: 'member-matheus',
        dueDate: addDays(5),
        tags: ['UI', 'Design System'],
        reports: [],
      },
    ],
    recentActivity: [
      {
        id: 'activity-1',
        title: 'Dashboard atualizado',
        description: 'Novos indicadores de progresso e busca por projeto adicionados.',
        createdAt: addDays(-1),
        tone: 'success',
      },
      {
        id: 'activity-2',
        title: 'Dependência de design',
        description: 'Faltam variantes finais de badge e navegação para concluir o project detail.',
        createdAt: addDays(-2),
        tone: 'warning',
      },
    ],
  },
  {
    id: 'client-onboarding',
    name: 'Client Onboarding Workspace',
    description:
      'Workspace para centralizar playbooks, responsáveis e sinais de risco no onboarding de novos clientes enterprise.',
    manager: 'Paulo Mendes',
    activeSprint: 'Sprint 05 · Capacitação',
    health: 'At risk',
    expectedEndDate: addDays(24),
    goals: [
      'Padronizar checklist de kickoff.',
      'Reduzir tempo para primeira entrega do time de implantação.',
    ],
    tags: ['Operações', 'Capacitação'],
    metrics: {
      velocity: 16,
      blocked: 2,
      throughput: 8,
    },
    members: [
      {
        id: 'member-paulo',
        name: 'Paulo Mendes',
        email: 'paulo@aggrandize.com',
        role: 'Operations Lead',
        level: 'Lead',
        workloadScore: 7,
        capacity: 11,
        workloadStatus: 'Healthy',
        focus: 'Remover gargalos de onboarding',
        availability: 'Busy',
      },
      {
        id: 'member-bruna',
        name: 'Bruna Lima',
        email: 'bruna@aggrandize.com',
        role: 'Customer Success',
        level: 'Senior',
        workloadScore: 11,
        capacity: 13,
        workloadStatus: 'Healthy',
        focus: 'Atualizar playbook de handoff',
        availability: 'Busy',
      },
    ],
    tasks: [
      {
        id: 'task-checklist',
        title: 'Mapear checklist por fase',
        description: 'Estruturar milestones do onboarding com responsáveis.',
        status: 'doing',
        difficulty: 5,
        progress: 60,
        priority: 'High',
        roleRequired: 'Customer Success',
        assigneeId: 'member-bruna',
        dueDate: addDays(2),
        tags: ['Onboarding'],
        reports: [],
      },
      {
        id: 'task-handoff',
        title: 'Revisar handoff comercial',
        description: 'Documentar insumos obrigatórios antes de mover para implantação.',
        status: 'blocked',
        difficulty: 3,
        progress: 20,
        priority: 'High',
        roleRequired: 'Operations Lead',
        assigneeId: 'member-paulo',
        dueDate: addDays(4),
        tags: ['Processo'],
        reports: [],
      },
      {
        id: 'task-playbook',
        title: 'Publicar novo playbook',
        description: 'Consolidar templates e acordos de SLA.',
        status: 'todo',
        difficulty: 2,
        progress: 0,
        priority: 'Medium',
        roleRequired: 'Operations Lead',
        dueDate: addDays(8),
        tags: ['Documentação'],
        reports: [],
      },
    ],
    recentActivity: [
      {
        id: 'activity-3',
        title: 'Risco de handoff detectado',
        description: 'Dependência com o time comercial está afetando o cronograma.',
        createdAt: addDays(-1),
        tone: 'warning',
      },
    ],
  },
  {
    id: 'internal-ops-ai',
    name: 'Internal Ops AI Assistant',
    description:
      'Experimento para resumir updates operacionais e sugerir priorização semanal para gestores.',
    manager: 'Renata Alves',
    activeSprint: 'Sprint 03 · Discovery',
    health: 'Needs attention',
    expectedEndDate: addDays(31),
    goals: [
      'Estruturar prompts e saídas com contexto confiável.',
      'Testar visão executiva semanal para managers.',
    ],
    tags: ['AI', 'Ferramentas internas'],
    metrics: {
      velocity: 9,
      blocked: 3,
      throughput: 4,
    },
    members: [
      {
        id: 'member-renata',
        name: 'Renata Alves',
        email: 'renata@aggrandize.com',
        role: 'Innovation Lead',
        level: 'Lead',
        workloadScore: 8,
        capacity: 11,
        workloadStatus: 'Healthy',
        focus: 'Conectar hipóteses do discovery com operação real',
        availability: 'Busy',
      },
      {
        id: 'member-igor',
        name: 'Igor Santos',
        email: 'igor@aggrandize.com',
        role: 'Full Stack Engineer',
        level: 'Mid',
        workloadScore: 12,
        capacity: 10,
        workloadStatus: 'Tight',
        focus: 'Unificar dados mockados com painéis gerenciais',
        availability: 'Blocked',
      },
    ],
    tasks: [
      {
        id: 'task-prompt',
        title: 'Validar prompt de resumo semanal',
        description: 'Checar qualidade da síntese gerada para diretoria.',
        status: 'doing',
        difficulty: 8,
        progress: 48,
        priority: 'High',
        roleRequired: 'Full Stack Engineer',
        assigneeId: 'member-igor',
        dueDate: addDays(7),
        tags: ['AI', 'Prompts'],
        reports: [],
      },
      {
        id: 'task-guardrails',
        title: 'Definir guardrails de contexto',
        description: 'Evitar respostas vagas e garantir transparência de fontes.',
        status: 'blocked',
        difficulty: 5,
        progress: 18,
        priority: 'High',
        roleRequired: 'Innovation Lead',
        assigneeId: 'member-renata',
        dueDate: addDays(5),
        tags: ['AI', 'Governança'],
        reports: [],
      },
      {
        id: 'task-readout',
        title: 'Desenhar readout executivo',
        description: 'Criar narrativa visual simples para líderes acompanharem experimentos.',
        status: 'todo',
        difficulty: 3,
        progress: 0,
        priority: 'Medium',
        roleRequired: 'Innovation Lead',
        dueDate: addDays(10),
        tags: ['Dashboard'],
        reports: [],
      },
    ],
    recentActivity: [
      {
        id: 'activity-4',
        title: 'Hipótese reavaliada',
        description: 'Descoberta indicou necessidade de mais contexto operacional antes do rollout.',
        createdAt: addDays(-3),
        tone: 'info',
      },
    ],
  },
];
